services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8090
      - NEW_TEMPLATES_ALLOWED=false
      - NEW_PERSONS_ALLOWED=true
    # ports:
    #   - 8090:8090
    volumes:
      - ./db:/app/db
